<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx9gK8x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx9gK8x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx9gK8x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx9gK8x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx9gK8x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx9gK8x',
    'container.build_id' => 'ac559938',
    'container.build_time' => 1616009585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx9gK8x');
