<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNJRhfuE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNJRhfuE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNJRhfuE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNJRhfuE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNJRhfuE\App_KernelDevDebugContainer([
    'container.build_hash' => 'NJRhfuE',
    'container.build_id' => '30ef0df3',
    'container.build_time' => 1617407091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNJRhfuE');
