<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2rJ7sAo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2rJ7sAo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2rJ7sAo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2rJ7sAo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2rJ7sAo\App_KernelDevDebugContainer([
    'container.build_hash' => '2rJ7sAo',
    'container.build_id' => '6f1dd826',
    'container.build_time' => 1615840347,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2rJ7sAo');
