<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'show_admin_home' => [[], ['_controller' => 'App\\Controller\\Admin\\HomeController::show'], [], [['text', '/administration']], [], []],
    'show_admin_messages' => [[], ['_controller' => 'App\\Controller\\Admin\\MessagesController::show'], [], [['text', '/messages']], [], []],
    'app_admin_messages_getallmessages' => [[], ['_controller' => 'App\\Controller\\Admin\\MessagesController::getAllMessages'], [], [['text', '/get-all-messages']], [], []],
    'show_admin_users' => [[], ['_controller' => 'App\\Controller\\Admin\\UsersController::show'], [], [['text', '/utilisateurs']], [], []],
    'app_admin_users_getallusers' => [[], ['_controller' => 'App\\Controller\\Admin\\UsersController::getAllUsers'], [], [['text', '/get-all-users']], [], []],
    'show_contact' => [[], ['_controller' => 'App\\Controller\\ContactController::show'], [], [['text', '/contact']], [], []],
    'show_gallery' => [[], ['_controller' => 'App\\Controller\\GalleryController::show'], [], [['text', '/galerie']], [], []],
    'show_home' => [[], ['_controller' => 'App\\Controller\\HomeController::show'], [], [['text', '/']], [], []],
    'show_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::show'], [], [['text', '/inscription']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
];
